import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          API handler on <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          You can see the implemented API requests below
        </p>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>{' '}
          <code className={styles.code}>/api/convert</code></h2>
            <p>POST; params:[Objects]; sends [Strings];</p>
          </a>

          <a href="" className={styles.card}>
            <h2>{' '}
          <code className={styles.code}>/api/results?currency=czk</code></h2>
            <p>GET; sends [Objects];</p>
          </a>

        
          <a href="" className={styles.card}>
            <h2>{' '}
          <code className={styles.code}>/api/results/export?currency=czk</code></h2>
            <p>GET; sends file;</p>
          </a>

          <a href="" className={styles.card}>
            <h2>{' '}
          <code className={styles.code}>/api/minmax</code></h2>
            <p>GET; sends Object of Type minmax;</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
